spring.application.name=store

# Server
spring.webflux.base-path=/store

# DDBB
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/store?currentSchema=store
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
logging.level.io.r2dbc.postgresql=DEBUG
logging.level.org.springframework.r2dbc.core=DEBUG

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://localhost:5432/store?currentSchema=store
spring.flyway.user=postgres
spring.flyway.password=postgres